# Generated by Django 4.2.7 on 2023-12-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email',
            new_name='profile1',
        ),
    ]
