# Generated by Django 4.2.7 on 2023-12-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='payment_status',
            field=models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('na', 'na')], default='na', max_length=20),
        ),
    ]
